### ISSUE TITLE
add a related paper

### ISSUE THREAD

**Issue by lfy79001** [OS-Agent-Survey/OS-Agent-Survey#2]
spider2-V, a benchmark
evaluating computer agents automate data science & engineering workflows

https://arxiv.org/abs/2407.10956

**Comment by OS-Agent-Survey** [comment]
Hi!
Spider2-V is truly a nice work and we found it already in the [Evaluation & Benchmark part of the full paper list](https://github.com/OS-Agent-Survey/OS-Agent-Survey?tab=readme-ov-file#evaluation--benchmark) (No. 16). Spider2-V is not yet included in the tables, as the survey is still a work in progress. But we plan to gradually **add all papers from the full paper list into the survey in the future**.
Thank you again for bringing this to our attention, and Merry Christmas!
(Btw, this paper is **rejected by arXiv** by so-called "does not contain sufficient original or substantive scholarly research", which is **definitely not the case and ridiculous**. Therefore, we are unable to provide an arXiv link. If possible, we’d greatly appreciate your support by sharing this repo with your friends or classmates. Thank u so much!)

**Comment by lfy79001** [comment]
Merry Christmas!
Looking forward to your great work!
